# Generated by Django 5.0 on 2023-12-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/user_image/avatar.png', null=True, upload_to='media/user_image'),
        ),
    ]
