# Generated by Django 5.0 on 2023-12-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='product_image/product.png', upload_to='Mobi_market/media/product_image', verbose_name='Фото товара'),
        ),
    ]
