# Generated by Django 5.0 on 2024-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_alter_productphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='product_image/product.png', upload_to='Mobi_market/media/product_image', verbose_name='Фото товара'),
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
