# Generated by Django 5.0 on 2024-01-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_photo_productphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(blank=True, default='product_image/product.png', null=True, upload_to='Mobi_market/media/product_image', verbose_name='Фото товара'),
        ),
    ]
